version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/app
    command: >
      sh -c "chmod +x wait_for_selenium.sh &&
             python3 wait_for_db.py &&
             alembic upgrade head"
    depends_on:
      - db
      - redis
      - selenium-chrome

  selenium-chrome:
    restart: unless-stopped
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "nc", "-z", "selenium-chrome", "4444" ]
      interval: 5s
      retries: 30

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env

  celery-beat:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/app
    command: celery -A scheduled_tasks beat --loglevel=INFO
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Kiev

  celery-worker:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Kiev
    command: celery -A scheduled_tasks worker --loglevel=INFO

  redis:
    restart: unless-stopped
    image: redis:latest
    environment:
      - TZ=Europe/Kiev
