"""Commit

Revision ID: b243bac02d9e
Revises: 
Create Date: 2023-10-13 08:39:34.288380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b243bac02d9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=511), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=127), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('image_url', sa.String(length=511), nullable=True),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.String(length=16), nullable=True),
    sa.Column('car_vin', sa.String(length=32), nullable=True),
    sa.Column('datetime_found', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
